GET http://10.10.20.7:3000/coa/activate/ab123456456
###

GET http://10.10.20.7:3000/coa/suspend/B00555

###
POST http://10.10.20.7:3000/coa/change-plan
Content-Type: application/json

{
    "username":"B00555",
    "newgroupname":"Dedicado 23 Mbps"
}