GET http://localhost:3000/coa/activate/e063da90277a
###

GET http://localhost:3000/coa/suspend/e063da90277a

###
POST http://10.10.20.7:3000/coa/change-plan
Content-Type: application/json

{
    "username":"B00555",
    "newgroupname":"Dedicado 23 Mbps"
}