POST http://localhost:3000/user-info
Content-Type: application/json

{
    "username": "18E8293B5C98",
    "firstname": "NPCA",
    "lastname": "2456",
    "groupname": "Banda Ancha RF 10 Mbps/2 Mbps",
    "creationby": "Francisco",
    "password":  "18E8293B5C99",
    "address": "DAYCO-RO-BORDE"
}
###
DELETE  http://localhost:3000/user-info/18E8293B5C99

###
PUT http://localhost:3000/user-info/17
Content-Type: application/json

{
    "name": "Juancito-Netcom",
    "username": "B00555",
    "firstname": "Cod-NC",
    "lastname": "7777",
    "groupname": "ftth residencial 30mg",
    "updateby": "tost",
    "creationby": "ast",
    "priority":  1,
    "address": "DAYCO-RO-BORDE"
}

###
POST  http://10.10.20.7:3000/user-info
Content-Type: application/json

{
    "username": "18E8293B5C99",
    "firstname": "NPCA",
    "lastname": "2456",
    "groupname": "Community Plus - Prebo 25 Mbps",
    "updateby": "Francisco",
    "creationby": "test",
    "password":  "18E8293B5C99"
}

###
GET http://localhost:3336/user-info/