FROM node as freeradius-api

# Instalar la CLI de NestJS globalmente en la imagen
RUN npm install -g @nestjs/cli

# Establecer el directorio de trabajo en la raíz de la aplicación
WORKDIR /app

# Copiar el archivo package.json y package-lock.json a la imagen
COPY package*.json ./

# Instalar las dependencias de la aplicación
RUN npm install

# Copiar el resto de los archivos de la aplicación a la imagen
COPY . .

ENV DB_DIALECT='mariadb'
ENV DB_HOST="host.docker.internal"
ENV DB_USERNAME="root"
ENV DB_PASSWORD="7448280"
ENV DB_NAME='nest'

EXPOSE 3003

CMD [ "npm", "run", "start:prod" ]
