POST http://localhost:3003/search
Content-Type: application/json

{
    "query": [1, 2, 3, 4, 5]
}

###

GET  http://10.10.20.7:3003/radcheck/page/1

###

POST http://10.10.20.7:3003/radcheck/
Content-Type: application/json

{
    "query": ["haraujo", "Hugo"]
}

###

POST http://10.10.20.7:3003/
Content-Type: application/json

{
    "username"  :	"Juancito",
    "password" :	"Rodriguez",
    "firstname" : "Juan",
    "lastname"  : "Rodriguez",
    "email"	  : "juan@vader.com",
    "mobilephone" : "4124-4563453",
    "value"	  : "456132",
    "creationby":"Fran",
    "groupname":"ftth",
    "priority":0

}
###
PUT http://localhost:3003/radusergroup
Content-Type: application/json

{
    "id":18,
    "username":"MiryS",
    "priority":99

}
###
curl -X POST -H "Content-Type: application/json" -d '{"username":"Comino","password":"lagata","firstname": "Lagata","lastname": "Comino","email": "eslagata@lagata.com","mobilephone": "4124-4563453","attribute": "gata","op": "==","value": "1","groupname" :"ftth","priority":1,"creationby":"admin"}' http://127.0.0.1:3003/




###
GET http://localhost:3003/coa/ls