GET http://localhost:3000/radusergroup

###

POST http://localhost:3000/radusergroup
Content-Type: application/json

{
    "username": "MONU0031944D",
    "groupname": "ftth"
}

###
POST http://localhost:3000/radusergroup/find
Content-Type: application/json

{
    "username": "MONU0031944D"
}

###
PUT http://localhost:3000/radusergroup/delete
Content-Type: application/json

{
    "username": "4561232",
    "groupname": "suspendido"
}