GET  http://10.10.20.7:3000/systems

###
GET  http://1.10.20.7:3000/systems/1/all

###
POST http://10.10.20.7:3000/systems
Content-Type: application/json

{
    "name":"Prueba Fran",
    "apiKey":"esunakey",
    "endPoint":"www.google.com"
}