GET http://10.10.20.7:3000/plan/

###
POST http://10.10.20.7:3000/plan
Content-Type: application/json

{
    "name":"ftth 700",
    "listName":"ftth 700"
}

###
PUT  http://10.10.20.7:3000/plan/1
Content-Type: application/json

{
    "name":"ftth 707",
    "listName":"ftth 707"
}

###
DELETE   http://localhost:3000/plan/6
Content-Type: application/json

{
    "name":"ftth 700",
    "listName":"ftth 700"
}