GET http://10.10.20.7:3000/services
###

PATCH  http://10.10.20.7:3000/services/1
Content-Type: application/json

{
    "sys":"2", 
    "clientId":3, 
    "plan":4, 
    "radiusId":1, 
    "status":1
    }

###
GET http://10.10.20.7:3000/services/sync/DAYCO-RO-BORDE
Content-Type: application/json