###
GET http://10.10.20.7:3000/nas
Content-Type: application/json

{
    "name":"Hola Mundo"
}


###
GET http://localhost:3000/nas/1


###

POST http://10.10.20.7:3000/nas
Content-Type: application/json

{
    "name":"Hola Mundo!",
    "ip_address": "8.8.8.8",
    "secret": "123",
    "server": "http://10.10.20.7/avisodecorte",
    "community": "suspendido"
}

###
PUT http://10.10.20.7:3000/nas/1
Content-Type: application/json

{
    "name":"Hello World!",
    "ip_address": "8.8.8.8",
    "secret": "123",
    "server": "http://10.10.20.7/avisodecorte",
    "community": "suspendido"
}