###

POST http://localhost:3000/zone
Content-Type: application/json

{
    "name":"Hello World!",
    "tlf": "55-555-5555",
    "codigo_zona": "The little waters",
    "nas": "1",
    "coord": "54321, 12345"
}


###

GET http://localhost:3000/zone
Content-Type: application/json

{
    "name":"Hello World!",
    "tlf": "55-555-5555",
    "codigo_zona": "The little waters",
    "nas": "1",
    "coord": "54321, 12345"
}


###

GET http://localhost:3000/zone/2
Content-Type: application/json

{
    "name":"Hola Mundo!",
    "tlf": "55-555-5555",
    "codigo_zona": "Las aguitas",
    "nas": "1",
    "coord": "12345, 54321"
}

###

PUT http://localhost:3000/zone/2
Content-Type: application/json

{
    "name":"hello world!",
    "tlf": "55-555-5555",
    "codigo_zona": "Las aguitas",
    "nas": 99,
    "coord": "12345, 54321"
}