###

POST http://localhost:3000/zone
Content-Type: application/json

{
    "name":"Hola Mundo!",
    "tlf": "55-555-5555",
    "codigo_zona": "Las aguitas",
    "Nas": "1",
    "coord": "12345, 54321"
}


###

GET http://localhost:3000/zone
Content-Type: application/json

{
    "name":"Hola Mundo!",
    "tlf": "55-555-5555",
    "codigo_zona": "Las aguitas",
    "Nas": "1",
    "coord": "12345, 54321"
}