GET http://localhost:3000/radcheck

###
GET http://localhost:3000/radcheck/17

###
PUT http://localhost:3000/radcheck/17
Content-Type: application/json

{
    "username": "Miry <3",
    "attribute": "Super Miry",
    "op": "==",
    "value": "Amazing"
}

###
POST http://localhost:3000/radcheck/
Content-Type: application/json

{
    "username": "Miry <3",
    "attribute": "Super Miry",
    "op": "==",
    "value": "Amazing"
}